[project]
name = "sentinel-rat-dashboard"
version = "0.1.0"
requires-python = ">=3.13"
description = "R Shiny dashboard for sentinel-rat project"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
authors = [
    { name="James Bowyer", email="ssc@iwr.uni-heidelberg.de" },
    { name="Tuyen Le", email="ssc@iwr.uni-heidelberg.de" },
]
dependencies = [
    "sqlalchemy>=2.0.51",
    "geoalchemy2>=0.20.0",
]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "pytest>=8.3.0",
    "pytest-cov>=5.0.0",
    "psycopg[binary]>=3.3.4",
    "testcontainers>=4.15.0",
]

[build-system]
requires = ["setuptools>=69.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]
