name: CI

on:
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python 3.13
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
                  cache: "pip"

            - name: Install dependencies
              run: pip install -e ".[dev]"

            - name: Run pytest
              run: pytest
              env:
                  TESTCONTAINERS_RYUK_DISABLED: true
